/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  overview: () => import("@/views/overview/index.vue"),
  system_backup_detail: () => import("@/views/system/backup/detail/[id].vue"),
  system_backup: () => import("@/views/system/backup/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  "system_op-log": () => import("@/views/system/op-log/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_settings: () => import("@/views/system/settings/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
